name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERPASS }}" | docker login -u kushalsrihair --password-stdin

      - name: Build and Push Docker Images
        run: |
          for dir in cart catalogue dispatch rating mongo mysql payment shipping user web load-gen fluent; do
            docker build -t kushalsrihair/$dir:v1 ./$dir
            docker push kushalsrihair/$dir:v1
          done
